# These are supported funding model platforms
# GitHub will display a "Sponsor" button in the repository sidebar

# GitHub Sponsors (GitHub maintains a list of these)
github: [acailic]
#### donta anny here as i didnt created them
### dont add any commynity as i didnt create them
